//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL2.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.IO;

    public partial class MVC_lab4Entities : DbContext
    {
        public MVC_lab4Entities()
            : base("name=MVC_lab4Entities")
        {
            using (StreamWriter sw = new StreamWriter(JsonPath + LogFile, true, System.Text.Encoding.Default))
            {
                sw.WriteLine("Model()");
            }
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PhoneNumbers> PhoneNumbers { get; set; }
    }
}
