//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL2.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneNumbers
    {
        public int id { get; set; }
        public string surname { get; set; }
        public string number { get; set; }
    }
}
